### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Samyak-Bumb** [rakibdev/material-code#1]
Please reduce curved (Reduce very less px because the curved edges are too big).
By the way Awesome, Best, Nice

**Comment by rakibdev** [comment]
Hi @Samyak-Bumb 
Just released v2.0.0 with more flexible customization. Radius can be now controlled using CSS --radius variable in settings. Default value is 20px.
![image](https://github.com/rakibdev/material-code/assets/60188988/f1d2c206-aec5-4662-b5a1-69fd706bf08a)

**Comment by ahmednrana** [comment]
Is this property still available?

**Comment by rakibdev** [comment]
@ahmednrana yes

![Image](https://github.com/user-attachments/assets/8ba5ba9d-7758-4ed7-a373-c08279d83acf)

**Comment by rakibdev** [comment]
@ahmednrana  available yes. the setting has been renamed to inject. not just css, but javascript can be added too.

![Image](https://github.com/user-attachments/assets/ebd00bcc-1679-42a6-8737-b6e62e2cd1c0)
