### ISSUE TITLE
Proxy `Element.prototype.attachShadow` might be better than `setTimeout`

### ISSUE THREAD

**Issue by RichardLuo0** [rakibdev/material-code#4]
https://github.com/rakibdev/material-code/blob/1e038f5601979c48d88359943a4533dad27c3c1e/extension.js#L257
I think you can do instead is like this:
https://github.com/RichardLuo0/vscode-frosted-glass-theme/blob/c4caecc9244230a3015a891d439b3a383f8a89cc/inject/vscode-frosted-glass-theme.js#L61-L67

**Comment by rakibdev** [comment]
@RichardLuo0 
you're right. added https://github.com/rakibdev/material-code/blob/main/inject.js#L1-L27
