### ISSUE TITLE
Command not found...

### ISSUE THREAD

**Issue by imcyruskw** [rakibdev/material-code#5]
I tried activating rounded corners and the other features using the command "Material Code: Apply styles" in the command pallet. Instead, it returned this.

![Screenshot 2024-01-14 191300](https://github.com/rakibdev/material-code/assets/138896326/5629cd46-0cdc-4b98-accd-f06d8f613577)

**Comment by rakibdev** [comment]
hi @imcyruskw
what is your vscode version?

**Comment by rakibdev** [comment]
@imcyruskw 
odd issue not able to reproduce.
what error does devtools show? open Help > Toggle Developer Tools. see if console shows any related error when running the command.

**Comment by imcyruskw** [comment]
@rakibdev
This is what shows up.
![image](https://github.com/rakibdev/material-code/assets/138896326/8be2567f-1b72-4258-89b1-76136dd9c670)

**Comment by imcyruskw** [comment]
@rakibdev any updates?

**Comment by rakibdev** [comment]
@imcyruskw fixed. try version [2.5.8](https://github.com/rakibdev/material-code/releases)

**Comment by imcyruskw** [comment]
@rakibdev it worked! Thank you!
